application: blogosaurus
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /blogosaurs/error-sadPizza\.jpg
  static_files: blogosaurs/error-sadPizza.jpg
  upload: blogosaurs/error-sadPizza.jpg

- url: /blogosaurs/mystylesheet\.css
  static_files: blogosaurs/mystylesheet.css
  upload: blogosaurs/mystylesheet.css

- url: /blogosaurs/blogosaurs\.html
  static_files: blogosaurs/blogosaurs.html
  upload: blogosaurs/blogosaurs.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
